sudo: required
services:
  - docker

before_install:
  - docker build -t girish/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true girish/docker-react-app npm run test -- --coverage 

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-mern-app"
  env: "DockerMernApp-env"
  bucket_name: "elasticbeanstalk-us-east-2-478964138354"
  bucket_path: "docker-mern-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
