language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t girish/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true girish/docker-react-app npm run test -- --coverage
